# Используем базовый образ nginx:1.22.1
FROM nginx:1.22.1

# Копируем файл nginx.conf в образ по пути /etc/nginx/templates/default.conf.template
COPY nginx.conf /etc/nginx/templates/default.conf.template
